FROM node:22.18.0-alpine

WORKDIR /app
EXPOSE 3000

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy source files
COPY . .

# Start in development mode with watch
CMD [ "npm", "run", "start:dev" ]
