import {
  GroupStatus,
  GroupVisibility,
} from '../../../../core/constants/constant';

export const groupSeedData = [
  {
    name: '[Published][Public][Require Approval] Tech Innovators',
    description: 'A group for technology enthusiasts and innovators',
    status: GroupStatus.Published,
    visibility: GroupVisibility.Public,
    location: 'San Francisco, CA',
    lat: 37.7749,
    lon: -122.4194,
    requireApproval: true,
  },
  {
    name: '[Pending][Public][Require Approval] Book Lovers Club',
    description: 'Discussing great literature and sharing book recommendations',
    status: GroupStatus.Pending,
    visibility: GroupVisibility.Public,
    location: 'New York, NY',
    lat: 40.7128,
    lon: -74.006,
    requireApproval: false,
  },
  {
    name: '[Draft][Public][Require Approval] Fitness Fanatics',
    description: 'For those who love to stay fit and share workout tips',
    status: GroupStatus.Draft,
    visibility: GroupVisibility.Public,
    location: 'Los Angeles, CA',
    lat: 34.0522,
    lon: -118.2437,
    requireApproval: true,
  },
  {
    name: '[Published][Authenticated][No approval] Culinary Explorers',
    description: 'Exploring culinary delights and sharing recipes',
    status: GroupStatus.Published,
    visibility: GroupVisibility.Authenticated,
    location: 'Chicago, IL',
    lat: 41.8781,
    lon: -87.6298,
    requireApproval: false,
  },
  {
    name: '[Pending][Authenticated][No approval] Outdoor Adventurers',
    description: 'Planning and sharing outdoor activities and adventures',
    status: GroupStatus.Pending,
    visibility: GroupVisibility.Authenticated,
    location: 'Denver, CO',
    lat: 39.7392,
    lon: -104.9903,
    requireApproval: false,
  },
  {
    name: '[Draft][Authenticated][No approval] Art Appreciation Society',
    description: 'Discussing and appreciating various forms of art',
    status: GroupStatus.Draft,
    visibility: GroupVisibility.Authenticated,
    location: 'Paris, France',
    lat: 48.8566,
    lon: 2.3522,
    requireApproval: false,
  },
  {
    name: '[Published][Private] Entrepreneurs Network',
    description:
      'Connecting and supporting aspiring and established entrepreneurs',
    status: GroupStatus.Published,
    visibility: GroupVisibility.Private,
    location: 'London, UK',
    lat: 51.5074,
    lon: -0.1278,
  },
  {
    name: '[Pending][Private] Green Earth Initiative',
    description: 'Promoting environmental awareness and sustainable living',
    status: GroupStatus.Pending,
    visibility: GroupVisibility.Private,
    location: 'Seattle, WA',
    lat: 47.6062,
    lon: -122.3321,
  },
  {
    name: '[Draft][Private] Photography Enthusiasts',
    description: 'Sharing photography tips, techniques, and amazing shots',
    status: GroupStatus.Draft,
    visibility: GroupVisibility.Private,
    location: 'Tokyo, Japan',
    lat: 35.6762,
    lon: 139.6503,
  },
];
