import {
  EventStatus,
  EventType,
  EventVisibility,
} from '../../../../core/constants/constant';

export const eventSeedData = [
  {
    name: '[admin][Draft][Public][Hybrid][Past][approvalQuestion] Tech Conference 2024',
    slug: 'tech-conference-2024',
    type: EventType.Hybrid,
    locationOnline: 'https://zoom.us/j/123456789',
    description:
      'Annual technology conference featuring the latest innovations in AI, blockchain, and IoT.',
    startDate: new Date('2024-09-15T09:00:00'),
    endDate: new Date('2024-09-17T18:00:00'),
    maxAttendees: 1000,
    location: 'Convention Center, Tech City',
    lat: 37.7749,
    lon: -122.4194,
    user: {
      id: 2,
    },
    status: EventStatus.Draft,
    visibility: EventVisibility.Public,
    approvalQuestion: 'Are you a developer?',
  },
  {
    name: '[admin][Pending][Authenticated][In-Person][Past][allowWaitlist] Local Art Exhibition',
    slug: 'local-art-exhibition',
    type: EventType.InPerson,
    description:
      'Showcasing works from local artists across various mediums including painting, sculpture, and photography.',
    startDate: new Date('2024-07-01T10:00:00'),
    endDate: new Date('2024-07-14T20:00:00'),
    maxAttendees: 200,
    location: 'City Art Gallery',
    lat: 40.7128,
    lon: -74.006,
    user: {
      id: 2,
    },
    status: EventStatus.Pending,
    visibility: EventVisibility.Authenticated,
    allowWaitlist: true,
  },
  {
    name: '[admin][Published][Public][Online][Upcoming][requireApproval] Virtual Book Club Meeting',
    slug: 'virtual-book-club-meeting',
    type: EventType.Online,
    locationOnline: 'https://meet.google.com/abc-defg-hij',
    description:
      "Monthly online gathering to discuss our latest book: '1984' by George Orwell.",
    startDate: new Date('2024-06-20T19:00:00'),
    endDate: new Date('2024-06-20T21:00:00'),
    maxAttendees: 50,
    user: {
      id: 2,
    },
    status: EventStatus.Published,
    visibility: EventVisibility.Private,
    requireApproval: true,
  },
  {
    name: '[admin][Draft][Public][In-Person][Past][requireGroupMembership] Charity Marathon',
    slug: 'charity-marathon',
    type: EventType.InPerson,
    description:
      "Annual charity run to raise funds for local children's hospital. 5K, 10K, and half-marathon options available.",
    startDate: new Date('2024-10-01T07:00:00'),
    endDate: new Date('2024-10-01T13:00:00'),
    maxAttendees: 5000,
    location: 'City Park',
    group: {
      id: 1,
    },
    user: {
      id: 2,
    },
    lat: 51.5074,
    lon: -0.1278,
    status: EventStatus.Draft,
    visibility: EventVisibility.Public,
    requireGroupMembership: true,
  },
  {
    name: '[admin][Pending][Private][Hybrid][Upcoming][approvalQuestion] Startup Pitch Night',
    slug: 'startup-pitch-night',
    type: EventType.Hybrid,
    locationOnline: 'https://twitch.tv/startup-pitch',
    description:
      'Ten promising startups pitch their ideas to a panel of venture capitalists and angel investors.',
    startDate: new Date('2024-12-05T18:00:00'),
    endDate: new Date('2024-12-05T22:00:00'),
    maxAttendees: 300,
    location: 'Innovation Hub',
    lat: 37.3382,
    lon: -121.8863,
    user: {
      id: 2,
    },
    status: EventStatus.Pending,
    visibility: EventVisibility.Private,
    approvalQuestion: 'Are you a startup?',
  },

  {
    name: '[admin][Published][Public][In-Person][Upcoming][allowWaitlist] Annual Food Festival',
    slug: 'annual-food-festival',
    type: EventType.InPerson,
    description:
      'A celebration of local and international cuisines. Features food stalls, cooking demonstrations, and eating contests.',
    startDate: new Date('2025-07-22T11:00:00'),
    endDate: new Date('2025-07-24T22:00:00'),
    maxAttendees: 1,
    location: 'City Square',
    lat: 48.8566,
    lon: 2.3522,
    user: {
      id: 2,
    },
    status: EventStatus.Published,
    visibility: EventVisibility.Public,
    allowWaitlist: true,
  },
  {
    name: '[admin][Draft][Public][Hybrid][Upcoming][requireGroupMembership] Virtual Reality Gaming Tournament',
    slug: 'vr-gaming-tournament',
    type: EventType.Hybrid,
    locationOnline: 'https://twitch.tv/vr-tournament',
    description:
      'Competitive VR gaming event featuring the latest in virtual reality technology. Both in-person and online participation available.',
    startDate: new Date('2024-12-10T09:00:00'),
    endDate: new Date('2024-12-12T18:00:00'),
    maxAttendees: 500,
    location: 'Tech Arena',
    group: {
      id: 1,
    },
    user: {
      id: 2,
    },
    lat: 37.4419,
    lon: -122.143,
    status: EventStatus.Draft,
    visibility: EventVisibility.Public,
    requireGroupMembership: true,
  },
  {
    name: '[admin][Pending][Private][In-Person][Upcoming][approvalQuestion][requireApproval] Mindfulness and Meditation Retreat',
    slug: 'mindfulness-meditation-retreat',
    type: EventType.InPerson,
    description:
      'A weekend of guided meditation, yoga, and mindfulness practices in a serene natural setting.',
    startDate: new Date('2024-08-18T14:00:00'),
    endDate: new Date('2024-08-20T12:00:00'),
    maxAttendees: 50,
    location: 'Tranquil Gardens Retreat Center',
    lat: 34.0522,
    lon: -118.2437,
    user: {
      id: 2,
    },
    status: EventStatus.Pending,
    visibility: EventVisibility.Private,
    approvalQuestion: 'Are you a mindfulness practitioner?',
    requireApproval: true,
  },
  {
    name: '[admin][Published][Public][Online][Upcoming][requireGroupMembership] Online Photography Workshop',
    slug: 'online-photography-workshop',
    type: EventType.Online,
    locationOnline: 'https://zoom.us/j/987654321',
    description:
      'Learn the basics of photography from professional photographers. Covers composition, lighting, and post-processing techniques.',
    startDate: new Date('2024-11-05T18:00:00'),
    endDate: new Date('2024-11-05T21:00:00'),
    maxAttendees: 100,
    user: {
      id: 2,
    },
    status: EventStatus.Published,
    visibility: EventVisibility.Public,
    requireGroupMembership: true,
    group: {
      id: 1,
    },
  },
  {
    name: '[admin][Published][Public][In-Person][Upcoming]] Sustainable Living Expo',
    slug: 'sustainable-living-expo',
    type: EventType.InPerson,
    description:
      'Explore eco-friendly products, attend workshops on sustainable practices, and learn about renewable energy solutions.',
    startDate: new Date('2024-10-15T10:00:00'),
    endDate: new Date('2024-10-17T18:00:00'),
    maxAttendees: 3000,
    location: 'Green Living Convention Center',
    lat: 52.3676,
    lon: 4.9041,
    user: {
      id: 2,
    },
    status: EventStatus.Published,
    visibility: EventVisibility.Public,
  },
];
